/**
 * Direct read access to Maccy's SwiftData SQLite database.
 *
 * Maccy stores clipboard history at:
 *   ~/Library/Application Support/Maccy/Storage.sqlite
 *
 * The schema is generated by SwiftData from the HistoryItem @Model class.
 * Table: ZHISTORYITEM (SwiftData prefixes with Z)
 * Columns: ZAPPLICATION, ZCATEGORY, ZCONTENTHASH, ZFIRSTCOPIEDAT,
 *          ZLASTCOPIEDAT, ZNUMBEROFCOPIES, ZPIN, ZTITLE
 *
 * Content blobs are in ZHISTORYITEMCONTENT with a foreign key to ZHISTORYITEM.
 */

import Database from 'better-sqlite3';
import { homedir } from 'os';
import { existsSync } from 'fs';
import { join } from 'path';

const DB_PATH = join(
  homedir(),
  'Library/Application Support/Maccy/Storage.sqlite'
);

export interface ClipboardItem {
  id: number;
  title: string;
  application: string | null;
  category: string | null;
  contentHash: string | null;
  firstCopiedAt: Date;
  lastCopiedAt: Date;
  numberOfCopies: number;
  pin: string | null;
}

export interface ClipboardContent {
  type: string;
  value: Buffer | null;
}

export class ClipboardDB {
  private db: Database.Database | null = null;

  open(): boolean {
    if (!existsSync(DB_PATH)) {
      return false;
    }
    // Open read-only — Maccy owns the writes
    this.db = new Database(DB_PATH, { readonly: true });
    this.db.pragma('journal_mode = WAL');
    return true;
  }

  close(): void {
    this.db?.close();
    this.db = null;
  }

  private ensureOpen(): Database.Database {
    if (!this.db) {
      if (!this.open()) {
        throw new Error(
          `Maccy database not found at ${DB_PATH}. Is Maccy installed?`
        );
      }
    }
    return this.db!;
  }

  /**
   * Detect whether the database uses SwiftData Z-prefixed schema
   * or a plain schema (varies by Maccy version).
   */
  private getTableName(): string {
    const db = this.ensureOpen();
    const tables = db
      .prepare(
        "SELECT name FROM sqlite_master WHERE type='table' AND name LIKE '%HISTORYITEM%'"
      )
      .all() as { name: string }[];

    // SwiftData uses ZHISTORYITEM
    if (tables.some((t) => t.name === 'ZHISTORYITEM')) return 'ZHISTORYITEM';
    // Newer SwiftData uses HISTORYITEM
    if (tables.some((t) => t.name === 'HISTORYITEM')) return 'HISTORYITEM';
    throw new Error('Could not find Maccy history table in database');
  }

  private getContentTableName(): string {
    const db = this.ensureOpen();
    const tables = db
      .prepare(
        "SELECT name FROM sqlite_master WHERE type='table' AND name LIKE '%HISTORYITEMCONTENT%'"
      )
      .all() as { name: string }[];

    if (tables.some((t) => t.name === 'ZHISTORYITEMCONTENT'))
      return 'ZHISTORYITEMCONTENT';
    if (tables.some((t) => t.name === 'HISTORYITEMCONTENT'))
      return 'HISTORYITEMCONTENT';
    throw new Error('Could not find Maccy content table in database');
  }

  /**
   * Get column names for the history table to handle schema differences.
   */
  private getColumns(): { prefix: string } {
    const db = this.ensureOpen();
    const tableName = this.getTableName();
    const info = db.prepare(`PRAGMA table_info(${tableName})`).all() as {
      name: string;
    }[];
    const colNames = info.map((c) => c.name);

    // SwiftData Z-prefix columns
    if (colNames.includes('ZTITLE')) return { prefix: 'Z' };
    // Plain columns
    if (colNames.includes('title')) return { prefix: '' };
    throw new Error('Unrecognized column schema');
  }

  /**
   * Get recent clipboard items, sorted by last copied time.
   */
  getHistory(limit = 50, offset = 0): ClipboardItem[] {
    const db = this.ensureOpen();
    const table = this.getTableName();
    const { prefix: p } = this.getColumns();

    const rows = db
      .prepare(
        `SELECT
        ${p === 'Z' ? 'Z_PK' : 'rowid'} as id,
        ${p}TITLE as title,
        ${p}APPLICATION as application,
        ${p}CATEGORY as category,
        ${p}CONTENTHASH as contentHash,
        ${p}FIRSTCOPIEDAT as firstCopiedAt,
        ${p}LASTCOPIEDAT as lastCopiedAt,
        ${p}NUMBEROFCOPIES as numberOfCopies,
        ${p}PIN as pin
      FROM ${table}
      ORDER BY ${p}LASTCOPIEDAT DESC
      LIMIT ? OFFSET ?`
      )
      .all(limit, offset) as any[];

    return rows.map((row) => ({
      id: row.id,
      title: row.title ?? '',
      application: row.application,
      category: row.category,
      contentHash: row.contentHash,
      firstCopiedAt: this.swiftDateToJS(row.firstCopiedAt),
      lastCopiedAt: this.swiftDateToJS(row.lastCopiedAt),
      numberOfCopies: row.numberOfCopies ?? 1,
      pin: row.pin,
    }));
  }

  /**
   * Search clipboard history by text content.
   */
  search(query: string, limit = 20): ClipboardItem[] {
    const db = this.ensureOpen();
    const table = this.getTableName();
    const { prefix: p } = this.getColumns();

    const rows = db
      .prepare(
        `SELECT
        ${p === 'Z' ? 'Z_PK' : 'rowid'} as id,
        ${p}TITLE as title,
        ${p}APPLICATION as application,
        ${p}CATEGORY as category,
        ${p}CONTENTHASH as contentHash,
        ${p}FIRSTCOPIEDAT as firstCopiedAt,
        ${p}LASTCOPIEDAT as lastCopiedAt,
        ${p}NUMBEROFCOPIES as numberOfCopies,
        ${p}PIN as pin
      FROM ${table}
      WHERE ${p}TITLE LIKE ? OR ${p}APPLICATION LIKE ? OR ${p}CATEGORY LIKE ?
      ORDER BY ${p}LASTCOPIEDAT DESC
      LIMIT ?`
      )
      .all(`%${query}%`, `%${query}%`, `%${query}%`, limit) as any[];

    return rows.map((row) => ({
      id: row.id,
      title: row.title ?? '',
      application: row.application,
      category: row.category,
      contentHash: row.contentHash,
      firstCopiedAt: this.swiftDateToJS(row.firstCopiedAt),
      lastCopiedAt: this.swiftDateToJS(row.lastCopiedAt),
      numberOfCopies: row.numberOfCopies ?? 1,
      pin: row.pin,
    }));
  }

  /**
   * Get pinned items.
   */
  getPinned(): ClipboardItem[] {
    const db = this.ensureOpen();
    const table = this.getTableName();
    const { prefix: p } = this.getColumns();

    const rows = db
      .prepare(
        `SELECT
        ${p === 'Z' ? 'Z_PK' : 'rowid'} as id,
        ${p}TITLE as title,
        ${p}APPLICATION as application,
        ${p}CATEGORY as category,
        ${p}CONTENTHASH as contentHash,
        ${p}FIRSTCOPIEDAT as firstCopiedAt,
        ${p}LASTCOPIEDAT as lastCopiedAt,
        ${p}NUMBEROFCOPIES as numberOfCopies,
        ${p}PIN as pin
      FROM ${table}
      WHERE ${p}PIN IS NOT NULL
      ORDER BY ${p}PIN`
      )
      .all() as any[];

    return rows.map((row) => ({
      id: row.id,
      title: row.title ?? '',
      application: row.application,
      category: row.category,
      contentHash: row.contentHash,
      firstCopiedAt: this.swiftDateToJS(row.firstCopiedAt),
      lastCopiedAt: this.swiftDateToJS(row.lastCopiedAt),
      numberOfCopies: row.numberOfCopies ?? 1,
      pin: row.pin,
    }));
  }

  /**
   * Get clipboard stats for insights.
   */
  getStats(): {
    totalItems: number;
    totalCopies: number;
    uniqueApps: number;
    categoryBreakdown: Record<string, number>;
    appBreakdown: Record<string, number>;
    topCopied: { title: string; count: number }[];
  } {
    const db = this.ensureOpen();
    const table = this.getTableName();
    const { prefix: p } = this.getColumns();

    const totalItems =
      (
        db
          .prepare(`SELECT COUNT(*) as c FROM ${table}`)
          .get() as { c: number }
      )?.c ?? 0;

    const totalCopies =
      (
        db
          .prepare(
            `SELECT SUM(${p}NUMBEROFCOPIES) as c FROM ${table}`
          )
          .get() as { c: number }
      )?.c ?? 0;

    const uniqueApps =
      (
        db
          .prepare(
            `SELECT COUNT(DISTINCT ${p}APPLICATION) as c FROM ${table} WHERE ${p}APPLICATION IS NOT NULL`
          )
          .get() as { c: number }
      )?.c ?? 0;

    // Category breakdown
    const catRows = db
      .prepare(
        `SELECT ${p}CATEGORY as cat, COUNT(*) as c FROM ${table}
       WHERE ${p}CATEGORY IS NOT NULL AND ${p}CATEGORY != ''
       GROUP BY ${p}CATEGORY ORDER BY c DESC`
      )
      .all() as { cat: string; c: number }[];
    const categoryBreakdown: Record<string, number> = {};
    for (const row of catRows) {
      categoryBreakdown[row.cat] = row.c;
    }

    // App breakdown
    const appRows = db
      .prepare(
        `SELECT ${p}APPLICATION as app, COUNT(*) as c FROM ${table}
       WHERE ${p}APPLICATION IS NOT NULL
       GROUP BY ${p}APPLICATION ORDER BY c DESC LIMIT 10`
      )
      .all() as { app: string; c: number }[];
    const appBreakdown: Record<string, number> = {};
    for (const row of appRows) {
      appBreakdown[row.app] = row.c;
    }

    // Top copied items
    const topRows = db
      .prepare(
        `SELECT ${p}TITLE as title, ${p}NUMBEROFCOPIES as count
       FROM ${table}
       WHERE ${p}NUMBEROFCOPIES > 1
       ORDER BY ${p}NUMBEROFCOPIES DESC LIMIT 10`
      )
      .all() as { title: string; count: number }[];

    return {
      totalItems,
      totalCopies,
      uniqueApps,
      categoryBreakdown,
      appBreakdown,
      topCopied: topRows.map((r) => ({
        title: (r.title ?? '').substring(0, 100),
        count: r.count,
      })),
    };
  }

  /**
   * SwiftData stores dates as seconds since 2001-01-01 (NSDate reference).
   */
  private swiftDateToJS(swiftTimestamp: number | null): Date {
    if (!swiftTimestamp) return new Date();
    // NSDate epoch: Jan 1, 2001 00:00:00 UTC
    const nsDateEpoch = Date.UTC(2001, 0, 1) / 1000;
    return new Date((nsDateEpoch + swiftTimestamp) * 1000);
  }
}
